/*
 * module function declaration for library sendermod header (autogenerated)
 */

#include "sendermod_module.h"

int sendermod_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=sender_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void sendermod_mod_cleanup(ubx_node_info_t* ni)
{
  sender_mod_cleanup(ni);
}

